In [9]:
import numpy as np
a=np.array([[1,2,3],[0,1,0],[0,0,1]])
b=np.array([[0,1,0],[1,0,0],[1,2,1]])
# A and B matrix

In [12]:
a.shape

(3, 3)

In [10]:
print(a+b)
#addition

[[1 3 3]
 [1 1 0]
 [1 2 2]]


In [13]:
#diff
print(a-b)


[[ 1  1  3]
 [-1  1  0]
 [-1 -2  0]]


In [15]:
#product1
print(a@b)
#product 2
print(np.matmul(a,b))


[[5 7 3]
 [1 0 0]
 [1 2 1]]
[[5 7 3]
 [1 0 0]
 [1 2 1]]


In [16]:
#transpose1
print(a.T)
#transpose2
print(np.transpose(a))


[[1 0 0]
 [2 1 0]
 [3 0 1]]
[[1 0 0]
 [2 1 0]
 [3 0 1]]


In [17]:
#determinant
print(np.linalg.det(a))
print(np.linalg.det(b))

1.0
-1.0


In [18]:
#finding Inverse
print(np.linalg.inv(a))

[[ 1. -2. -3.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [19]:
#finding trace
print(np.linalg.trace(a))
print(np.linalg.trace(b))


3
1


In [20]:
#rank
print(np.linalg.matrix_rank(a))
print(np.linalg.matrix_rank(b))


3
3


In [22]:
#finding eigen value and eigen vector
print(np.linalg.eig(a))
print(np.linalg.eig(b))

EigResult(eigenvalues=array([1., 1., 1.]), eigenvectors=array([[ 1.00000000e+00, -1.00000000e+00, -1.00000000e+00],
       [ 0.00000000e+00,  1.11022302e-16,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  7.40148683e-17]]))
EigResult(eigenvalues=array([ 1.,  1., -1.]), eigenvectors=array([[ 0.00000000e+00,  7.40148683e-17,  6.66666667e-01],
       [ 0.00000000e+00,  7.40148683e-17, -6.66666667e-01],
       [ 1.00000000e+00, -1.00000000e+00,  3.33333333e-01]]))
